from __future__ import annotations

import pickle
from pathlib import Path

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression


def _build_training_data() -> tuple[list[str], list[str]]:
    invoice_samples = [
        "tax invoice invoice number inv-1021 date 12/03/2026 total amount rs 12500 payment due 25/03/2026",
        "invoice # 8871 vendor alpha systems bill to novatech subtotal 8900 gst 1602 grand total 10502",
        "proforma invoice no pr-9002 issue date 01-02-2026 total payable inr 7300 banking details included",
        "purchase invoice order po-45 quantity 15 unit cost 450 amount 6750 due date 15-04-2026",
        "service invoice number sr-557 consulting hours 18 rate 1200 total inr 21600 tax included",
        "retail invoice inv2026-120 store id 18 invoice date 11/01/2026 amount due 4560",
        "freelance billing invoice no fl-77 project ui redesign total amount usd 1200",
        "invoice reference 2209 client apex corp line items hosting maintenance total 9400",
        "invoice details bill no b-290 payment terms net 30 grand total 15999",
        "gst invoice id g-1001 cgst sgst subtotal and final payable amount 18250",
        "supplier invoice no sup-505 date 03/07/2026 amount rs 9450 purchase department",
        "invoice line item software license annual fee total 68000 invoice number lic-83",
        "e-invoice ack number 44231 invoice number ei-98 amount 14320 generated by erp",
        "invoice receipt bill to city hospital invoice date 21-06-2026 amount 3700",
        "professional invoice number 212 consultancy charge amount 25000 payment mode bank transfer",
        "tax bill invoice id tx-321 total amount 5275 due 10/10/2026",
        "invoice for logistics shipment id sh-778 amount payable 11240 invoice no lg-331",
        "billing statement invoice no st-03 invoice amount inr 8640 discount 5 percent",
    ]

    resume_samples = [
        "resume name ananya sharma skills python sql machine learning education bachelor of technology university",
        "curriculum vitae profile data scientist experience nlp deep learning projects aws certifications",
        "candidate resume objective software engineer internship java spring boot teamwork communication",
        "resume summary analyst with excel sql tableau education master degree in business analytics",
        "professional resume technical skills c plus plus python docker kubernetes cloud",
        "cv education bsc computer science college projects classification recommendation system",
        "resume contains work history frontend developer react javascript html css leadership",
        "candidate profile skills problem solving communication stakeholder management mba university",
        "resume objective ai engineer publications nlp transformers pytorch education phd",
        "work experience full stack developer flask django rest api mysql skills",
        "resume highlights aws solutions architect certification devops ci cd terraform",
        "curriculum vitae internship at fintech company fraud detection project and data cleaning",
        "resume education bachelor degree cgpa 8.7 college of engineering",
        "resume skills data analysis statistics hypothesis testing r python",
        "candidate cv includes achievements hackathon winner open source contributor",
        "professional profile teacher transitioned to data analyst with sql power bi and python",
        "resume details contact education master of science university and technical skills",
        "resume summary product manager with agile scrum stakeholder communication and analytics skills",
    ]

    report_samples = [
        "project report executive summary introduction methodology analysis findings conclusion recommendations",
        "annual report section one financial overview risk analysis board observations conclusion",
        "research report abstract introduction literature review methods results discussion conclusion",
        "market intelligence report heading executive summary competitor analysis strategic insights",
        "incident report introduction timeline root cause analysis corrective action conclusion",
        "quality audit report scope observations non conformity findings recommendations",
        "technical report section 1 architecture section 2 benchmarking section 3 results",
        "quarterly performance report overview metrics analysis trend conclusion",
        "sustainability report environmental impact social governance initiatives and yearly conclusion",
        "lab report objective procedure observation result inference discussion",
        "business report chapter methodology data interpretation strategic recommendations",
        "feasibility report problem statement assumptions cost benefit analysis conclusion",
        "survey report introduction respondent demographics findings and insights",
        "policy report executive summary background analysis recommendation section",
        "field visit report date location observations and final remarks",
        "compliance report inspection checklist deviations corrective measures",
        "weekly status report accomplished tasks blockers next plan",
        "deep dive report section overview, section metrics, section recommendation",
    ]

    texts = invoice_samples + resume_samples + report_samples
    labels = (["invoice"] * len(invoice_samples)) + (["resume"] * len(resume_samples)) + (["report"] * len(report_samples))
    return texts, labels


def train_and_save_model() -> tuple[LogisticRegression, TfidfVectorizer]:
    texts, labels = _build_training_data()
    vectorizer = TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=1,
        max_features=5000,
        sublinear_tf=True,
    )
    features = vectorizer.fit_transform(texts)

    model = LogisticRegression(max_iter=1200, solver="liblinear")
    model.fit(features, labels)

    model_dir = Path(__file__).resolve().parent
    with open(model_dir / "model.pkl", "wb") as model_file:
        pickle.dump(model, model_file)
    with open(model_dir / "vectorizer.pkl", "wb") as vectorizer_file:
        pickle.dump(vectorizer, vectorizer_file)

    print("Training complete. Saved model.pkl and vectorizer.pkl")
    return model, vectorizer


if __name__ == "__main__":
    train_and_save_model()
